use_frameworks!

platform :ios, '9.0'

target 'IMDynamicMoudle_Example' do
  pod 'IMDynamicMoudle', :path => '../'
  pod 'IMBeeHive', :path => '../../IMBeeHive'

  target 'IMDynamicMoudle_Tests' do
    inherit! :search_paths

    
  end
end
